CREATE TABLE training_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    duration_minutes INTEGER NOT NULL,
    notes VARCHAR(1000),
    training_date DATE NOT NULL,
    type VARCHAR(255) NOT NULL,

    CONSTRAINT training_sessions_pkey
        PRIMARY KEY (id),

    CONSTRAINT training_sessions_type_check
        CHECK (type IN ('RUNNING', 'BOULDERING', 'STRENGTH'))
);