CREATE TABLE running_details (
    session_id BIGINT PRIMARY KEY,
    run_type VARCHAR(30) NOT NULL,
    distance_meters INTEGER NOT NULL,
    elapsed_seconds INTEGER NOT NULL,
    average_heart_rate INTEGER,
    max_heart_rate INTEGER,

    CONSTRAINT running_details_session_fk
        FOREIGN KEY (session_id)
        REFERENCES training_sessions (id)
        ON DELETE CASCADE,

    CONSTRAINT running_details_type_check
        CHECK (
            run_type IN (
                'EASY',
                'TEMPO',
                'INTERVAL',
                'LONG_RUN',
                'RECOVERY',
                'RACE',
                'OTHER'
            )
        ),

    CONSTRAINT running_details_distance_check
        CHECK (distance_meters > 0),

    CONSTRAINT running_details_time_check
        CHECK (elapsed_seconds > 0),

    CONSTRAINT running_details_average_hr_check
        CHECK (
            average_heart_rate IS NULL
            OR average_heart_rate BETWEEN 30 AND 250
        ),

    CONSTRAINT running_details_max_hr_check
        CHECK (
            max_heart_rate IS NULL
            OR max_heart_rate BETWEEN 30 AND 250
        ),

    CONSTRAINT running_details_hr_order_check
        CHECK (
            average_heart_rate IS NULL
            OR max_heart_rate IS NULL
            OR max_heart_rate >= average_heart_rate
        )
);


CREATE TABLE bouldering_grade_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    grade VARCHAR(4) NOT NULL,
    attempted_count INTEGER NOT NULL,
    completed_count INTEGER NOT NULL,

    CONSTRAINT bouldering_grade_results_pkey
        PRIMARY KEY (id),

    CONSTRAINT bouldering_grade_results_session_fk
        FOREIGN KEY (session_id)
        REFERENCES training_sessions (id)
        ON DELETE CASCADE,

    CONSTRAINT bouldering_grade_results_grade_check
        CHECK (
            grade IN (
                'VB',
                'V0', 'V1', 'V2', 'V3', 'V4',
                'V5', 'V6', 'V7', 'V8', 'V9',
                'V10', 'V11', 'V12', 'V13',
                'V14', 'V15', 'V16', 'V17'
            )
        ),

    CONSTRAINT bouldering_attempted_count_check
        CHECK (attempted_count >= 0),

    CONSTRAINT bouldering_completed_count_check
        CHECK (
            completed_count >= 0
            AND completed_count <= attempted_count
        ),

    CONSTRAINT bouldering_session_grade_unique
        UNIQUE (session_id, grade)
);


CREATE TABLE strength_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    exercise_name VARCHAR(100) NOT NULL,
    exercise_order INTEGER NOT NULL,

    CONSTRAINT strength_exercises_pkey
        PRIMARY KEY (id),

    CONSTRAINT strength_exercises_session_fk
        FOREIGN KEY (session_id)
        REFERENCES training_sessions (id)
        ON DELETE CASCADE,

    CONSTRAINT strength_exercises_name_check
        CHECK (length(trim(exercise_name)) > 0),

    CONSTRAINT strength_exercises_order_check
        CHECK (exercise_order > 0),

    CONSTRAINT strength_exercises_order_unique
        UNIQUE (session_id, exercise_order)
);


CREATE TABLE strength_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exercise_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    repetitions INTEGER NOT NULL,
    weight_kg NUMERIC(6, 2) NOT NULL,

    CONSTRAINT strength_sets_pkey
        PRIMARY KEY (id),

    CONSTRAINT strength_sets_exercise_fk
        FOREIGN KEY (exercise_id)
        REFERENCES strength_exercises (id)
        ON DELETE CASCADE,

    CONSTRAINT strength_sets_number_check
        CHECK (set_number > 0),

    CONSTRAINT strength_sets_repetitions_check
        CHECK (repetitions > 0),

    CONSTRAINT strength_sets_weight_check
        CHECK (weight_kg >= 0),

    CONSTRAINT strength_sets_number_unique
        UNIQUE (exercise_id, set_number)
);