CREATE TABLE training_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(120) NOT NULL,

    metric VARCHAR(64) NOT NULL,

    target_value NUMERIC(12, 2) NOT NULL,

    exercise_name VARCHAR(120),

    target_date DATE,

    created_at DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT training_goals_metric_check
        CHECK (
            metric IN (
                'RUNNING_DISTANCE_KM',
                'RUNNING_PACE_SECONDS_PER_KM',
                'BOULDERING_GRADE',
                'STRENGTH_WEIGHT_KG'
            )
        ),

    CONSTRAINT training_goals_target_positive_check
        CHECK (target_value > 0),

    CONSTRAINT training_goals_bouldering_grade_check
        CHECK (
            metric <> 'BOULDERING_GRADE'
            OR (
                target_value BETWEEN 0 AND 17
                AND target_value = TRUNC(target_value)
            )
        ),

    CONSTRAINT training_goals_exercise_check
        CHECK (
            (
                metric = 'STRENGTH_WEIGHT_KG'
                AND exercise_name IS NOT NULL
                AND BTRIM(exercise_name) <> ''
            )
            OR (
                metric <> 'STRENGTH_WEIGHT_KG'
                AND exercise_name IS NULL
            )
        )
);

CREATE INDEX training_goals_metric_index
    ON training_goals (metric);

CREATE INDEX training_goals_target_date_index
    ON training_goals (target_date);